### ISSUE TITLE
Example of client-side code taking over?

### ISSUE THREAD

**Issue by dupski** [developit/preact-render-to-string#9]
I'm currently having an issue where preact on the client-side is not taking over the DOM nodes rendered by preact-render-to-string on the server. Am I missing something or does preact not currently take over pre-rendered HTML?

On the server, the content is rendered (by Nunjucks):

`<div id="header">{{headerHtml | safe}}</div>`

(where `headerHtml` is the output of render-to-string)

On the client, I'm then doing:

```
render((
	<Header ... />
), document.querySelector('#header'));
```
And the header ends up being duplicated.

**Comment by developit** [comment]
Hi @dupski - preact definitely supports this! There is just one slight difference between Preact and React here that's causing the duplication.  Instead of attempting to find and update a previously rendered DOM (which is a guess at best), Preact actually gives you absolute control over what happens:  if you want to _replace_ an element with your client-side-rendered one, you just pass the existing element as a third argument to render.  Here's your example modified to work:

```js
// the parent we're rendering into:
let header = document.querySelector('#header');

render((
    <Header ... />
), header, header.firstElementChild);
```

`.firstElementChild` will be your server-rendered stuff (`headerHtml`).  Let me know if that works!

**Comment by developit** [comment]
@dupski Here's two examples on CodePen showing how that third argument tells preact to replace the existing DOM with your client-side rendered one:

http://codepen.io/developit/pen/adKzPj?editors=0010#0
http://codepen.io/developit/pen/QEVpzz?editors=1010

I'll close this out since I'm confident this fixes the issue at hand, but please feel free to keep chatting!  There are also great people in the [Preact Gitter room](https://gitter.im/developit/preact) 😊

**Comment by dupski** [comment]
Thanks @developit, works perfectly. I will check out the Gitter before raising an issue next time. Cheers!

**Comment by developit** [comment]
No worries, this has the benefit of showing up now when someone Google the same error in a month :)
